name = "test-provisioning"
main = "src/index.js"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[r2_buckets]]
binding = "FOOOOOO"
bucket_name = "fooooo"